---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      vm_hostname: test-kitchen.jamestheaweso.me
    run_list:
      - recipe[base::default]
    attributes:
