---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/fixtures/data_bags"
    driver:
      vm_hostname: test-kitchen.jamestheaweso.me
    run_list:
      - recipe[base::default]
      - recipe[chef-solo-search]
    attributes:
