---
AllCops:
  Exclude:
    - Berksfile
    - .kitchen.yml
    - .kitchen/**/*
    - Thorfile
    - test/**/*
    - spec/**/*
    - metadata.rb
    - Vagrantfile
    - cookbooks/**/*

LineLength:
  Max: 160
