language: ruby
rvm:
  - 2.1.2
  - 2.1.4
bundler_args: --jobs 7
gemfile:
  - Gemfile
before_script: bundle exec berks vendor cookbooks
script: 
  - bundle exec knife cookbook test $COOKBOOK
  - bundle exec foodcritic -G -f any -X spec/ $SANDBOX/$COOKBOOK
  - bundle exec rspec 
  - bundle exec rubocop
