source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef', '~> 12.6.0'
gem 'chefspec', '>=3'
gem 'foodcritic'
gem 'highline'
gem 'kitchen-vagrant', '>= 0.15.0'
gem 'rspec'
gem 'rubocop'
gem 'serverspec'
gem 'test-kitchen'
