name             'base'
maintainer       'James Awesome'
maintainer_email 'james@wesome.nyc'
license          'Do what you want, don\'t come cryin\''
description      'Configures the base system'
long_description 'Configures the base system'
version          '0.1.1'

depends 'hostname'
depends 'users'
depends 'chef-client'
